language: java
jdk:
  - openjdk11

branches:
  only:
    - master

#travis CI server home###
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r jwuser00-springboot *
  - mkdir -p deploy
  - mv jwuser00-springboot.zip deploy/jwuser00-springboot.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: jwuser00-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

notifications:
  email:
    recipients:
      - jwuser00@gamil.com